### ISSUE TITLE
Brighterscript on the horizon at all?

### ISSUE THREAD

**Issue by jfrux** [getndazn/kopytko-framework#23]
Curious if you had any thoughts on brighterscript integration at all in the future or if so, would you be interested in myself helping to make it happen?

I've gotten really used to the nice syntax of brighterscript and it makes things feel very clean and integrated so wasn't sure if you had considered it at all?

**Comment by pawelhertman** [comment]
Hey @jfrux , thanks for your interest and potential support!

We already passed a phase of swearing for the BrightScript syntax looking for other solutions and BrighterScript was really tempting to use. We ended with a feeling that in such a small community of BS language creating a transpileable language and maintaining it can be tricky so we do have not enough trust in such movement.

We had an attempt to use ROPM as the importing system, even created a few PRs but we found too many difficulties and required changes to achieve our goals (which we didn't fully achieve yet). I'm mentioning this because it would close us to use brighterscript in the project by default.

Also, as the whole Kopytko Ecosystem is kinda opinionated, we didn't want to enforce its users to use BrighterScript. However, if we did it, we would do it as a plugin thanks to the packager's plugins mechanism. So if this is something you need or find helpful for other users, we encourage you to create a public plugin for the packager with a BrighterScript transpilation action. If you decide to do it, please let us know so we can help you by making a code review and link to your plugin in the docs :)

Sorry for a delayed response

**Comment by jfrux** [comment]
Wow! Thank you so much for the detailed response.
I really appreciate it!

No worries on not buying into it.  I fully understand!

I tried to get started using this on a project but I did find that I had trouble understanding the best places to put some of my logic.  It had a quick on-boarding experience but felt limited quickly.  Is that normal? Are there any examples you know of that make use of more advanced UI techniques?

**Comment by pawelhertman** [comment]
Thank you for your opinion. I get your point - even if it's quite opinionated, it still has not enough real-life examples. I think my example app could help you: [https://github.com/pawelhertman/kopytko-example-app](https://github.com/pawelhertman/kopytko-example-app). It shows a lot of possibilities and advantages of Kopytko Framework, Utils, and Packager. Please keep in mind it's not an official example app. The official one is in our backlog.

**Comment by jfrux** [comment]
No worries at all! Thank you for sharing this! Will take a look.
I’m happy you’re working on this.  It is a much needed effort in this community to have something more rapid to develop on.  Really do appreciate your efforts!

Keep it up!

From: Paweł Hertman ***@***.***>
Date: Thursday, March 24, 2022 at 9:07 AM
To: getndazn/kopytko-framework ***@***.***>
Cc: jfrux ***@***.***>, Mention ***@***.***>
Subject: Re: [getndazn/kopytko-framework] Brighterscript on the horizon at all? (Issue #23)

Thank you for your opinion. I get your point - even if it's quite opinionated, it still has not enough real-life examples. I think my example app could help you: https://github.com/pawelhertman/kopytko-example-app. It shows a lot of possibilities and advantages of Kopytko Framework, Utils, and Packager. Please keep in mind it's not an official example app. The official one is in our backlog.

**Comment by pawelhertman** [comment]
Thanks :) Is there anything else we could help you with in terms of the topic of this "issue"? If not, I'm gonna close it. Feel free to join our [slack](https://join.slack.com/t/kopytko-group/shared_invite/zt-15xqo4o51-sFkRi~OAbsuLvWOzOPln4Q) when seeking help.
